### ISSUE TITLE
add DecentHolograms

### ISSUE THREAD

**Issue by Link0Darck** [IntellectualSites/HoloPlots#191]
### What feature do you want to see added?

Hello,
I'm asking this because Holographic Displays is starting to be abandoned and should move on to something else like (DecentHolograms) please thank you in advance for the work.
Sincerely

### Are there any alternatives?

yes DecentHolograms

**Comment by PierreSchwang** [comment]
Already supported.

**Comment by Link0Darck** [comment]
I do not believe !

**Comment by Link0Darck** [comment]
```
[02:36:06] [Server thread/ERROR]: Could not load 'plugins/HoloPlots-7.0.0.jar'
org.bukkit.plugin.UnknownDependencyException: Unknown dependency HolographicDisplays. Please download and install HolographicDisplays to run this plugin.
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:279) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:121) ~[spigot-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R4.CraftServer.loadPlugins(CraftServer.java:431) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:232) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1010) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by Link0Darck** [comment]
so you can open and report it as a bug 🤣

**Comment by PierreSchwang** [comment]
It would work, if you would use the latest version - which is 7.1.0 not 7.0.0 (https://modrinth.com/plugin/holoplots)

So no, I'll not reopen.

**Comment by Link0Darck** [comment]
> It would work, if you would use the latest version - which is 7.1.0 not 7.0.0 (https://modrinth.com/plugin/holoplots)
> 
> So no, I'll not reopen.

I just noticed then I updated the plugin then I got this error.

```
[03:17:41] [Server thread/ERROR]: [HoloPlots] Failed to update hologram @ plotworld;0;0
java.util.concurrent.CompletionException: eu.decentsoftware.holograms.libs.nbtapi.NbtApiException: [?][2.12.2]Error while calling the method 'contains(java.lang.String)', loaded: true, Enum: COMPOUND_HAS_KEY, Passed Class: class net.minecraft.world.item.EnumAnimation
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at com.plotsquared.bukkit.util.task.BukkitPlotSquaredTask.runTask(BukkitPlotSquaredTask.java:39) ~[?:?]
        at com.plotsquared.core.util.task.PlotSquaredTask.run(PlotSquaredTask.java:44) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R4.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at org.bukkit.craftbukkit.v1_20_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1397) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:402) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1293) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1064) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:311) ~[spigot-1.20.6-R0.1-SNAPSHOT.jar:4156-Spigot-e2c1eee-428aefe]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: eu.decentsoftware.holograms.libs.nbtapi.NbtApiException: [?][2.12.2]Error while calling the method 'contains(java.lang.String)', loaded: true, Enum: COMPOUND_HAS_KEY, Passed Class: class net.minecraft.world.item.EnumAnimation
        at eu.decentsoftware.holograms.libs.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:386) ~[?:?]
        at eu.decentsoftware.holograms.libs.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:626) ~[?:?]
        at eu.decentsoftware.holograms.libs.nbtapi.NBTCompound.hasTag(NBTCompound.java:720) ~[?:?]
        at eu.decentsoftware.holograms.api.utils.items.HologramItem.fromItemStack(HologramItem.java:147) ~[?:?]
        at eu.decentsoftware.holograms.api.DHAPI.addHologramLine(DHAPI.java:353) ~[?:?]
        at com.plotsquared.holoplots.provider.impl.DecentHologramsProvider.createHologram(DecentHologramsProvider.java:32) ~[?:?]
        at com.plotsquared.holoplots.provider.HologramProvider.createOrUpdateHologram(HologramProvider.java:69) ~[?:?]
        at com.plotsquared.holoplots.DefaultHoloPlots.lambda$updatePlot$3(DefaultHoloPlots.java:182) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        ... 11 more
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:197) ~[?:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:99) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at eu.decentsoftware.holograms.libs.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:383) ~[?:?]
        at eu.decentsoftware.holograms.libs.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:626) ~[?:?]
        at eu.decentsoftware.holograms.libs.nbtapi.NBTCompound.hasTag(NBTCompound.java:720) ~[?:?]
        at eu.decentsoftware.holograms.api.utils.items.HologramItem.fromItemStack(HologramItem.java:147) ~[?:?]
        at eu.decentsoftware.holograms.api.DHAPI.addHologramLine(DHAPI.java:353) ~[?:?]
        at com.plotsquared.holoplots.provider.impl.DecentHologramsProvider.createHologram(DecentHologramsProvider.java:32) ~[?:?]
        at com.plotsquared.holoplots.provider.HologramProvider.createOrUpdateHologram(HologramProvider.java:69) ~[?:?]
        at com.plotsquared.holoplots.DefaultHoloPlots.lambda$updatePlot$3(DefaultHoloPlots.java:182) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        ... 11 more
```

**Comment by PierreSchwang** [comment]
That's no error by HoloPlots. Try updating DecentHolograms (a new update was published just today) or get in touch with them.
